ALTER TABLE "advisor_profiles" DROP CONSTRAINT "advisor_profiles_penalty_points_nonnegative", ADD CONSTRAINT "advisor_profiles_penalty_points_nonnegative" CHECK ("penalty_points" >= 0);--> statement-breakpoint
ALTER TABLE "service_images" DROP CONSTRAINT "service_images_carousel_index_nonnegative", ADD CONSTRAINT "service_images_carousel_index_nonnegative" CHECK ("carousel_index" >= 0);--> statement-breakpoint
ALTER TABLE "services" DROP CONSTRAINT "services_price_satang_nonnegative", ADD CONSTRAINT "services_price_satang_nonnegative" CHECK ("price_satang" >= 0);--> statement-breakpoint
ALTER TABLE "services" DROP CONSTRAINT "services_duration_minutes_positive", ADD CONSTRAINT "services_duration_minutes_positive" CHECK ("duration_minutes" > 0);--> statement-breakpoint
ALTER TABLE "services" DROP CONSTRAINT "services_trial_duration_consistent", ADD CONSTRAINT "services_trial_duration_consistent" CHECK (("trial_enabled" AND "trial_duration_minutes" > 0) OR (NOT "trial_enabled" AND "trial_duration_minutes" IS NULL));--> statement-breakpoint
ALTER TABLE "screening_requests" DROP CONSTRAINT "screening_requests_trial_window_valid", ADD CONSTRAINT "screening_requests_trial_window_valid" CHECK (("trial_started_at" IS NULL AND "trial_expires_at" IS NULL) OR ("trial_started_at" IS NOT NULL AND "trial_expires_at" IS NOT NULL AND "trial_expires_at" > "trial_started_at"));--> statement-breakpoint
ALTER TABLE "service_screening_questions" DROP CONSTRAINT "service_screening_questions_display_order_nonnegative", ADD CONSTRAINT "service_screening_questions_display_order_nonnegative" CHECK ("display_order" >= 0);--> statement-breakpoint
ALTER TABLE "service_reviews" DROP CONSTRAINT "service_reviews_stars_range", ADD CONSTRAINT "service_reviews_stars_range" CHECK ("stars" BETWEEN 1 AND 5);--> statement-breakpoint
ALTER TABLE "service_timeslots" DROP CONSTRAINT "service_timeslots_end_after_start", ADD CONSTRAINT "service_timeslots_end_after_start" CHECK ("end_time" > "start_time");--> statement-breakpoint
ALTER TABLE "payouts" DROP CONSTRAINT "payouts_amount_satang_positive", ADD CONSTRAINT "payouts_amount_satang_positive" CHECK ("amount_satang" > 0);--> statement-breakpoint
ALTER TABLE "service_invoices" DROP CONSTRAINT "service_invoices_amount_satang_nonnegative", ADD CONSTRAINT "service_invoices_amount_satang_nonnegative" CHECK ("amount_satang" >= 0);--> statement-breakpoint
ALTER TABLE "service_invoices" DROP CONSTRAINT "service_invoices_platform_fee_range", ADD CONSTRAINT "service_invoices_platform_fee_range" CHECK ("platform_fee_satang" BETWEEN 0 AND "amount_satang");--> statement-breakpoint
ALTER TABLE "chat_files" DROP CONSTRAINT "chat_files_size_range", ADD CONSTRAINT "chat_files_size_range" CHECK ("file_size_bytes" BETWEEN 1 AND 52428800);--> statement-breakpoint
ALTER TABLE "off_platform_flags" DROP CONSTRAINT "off_platform_flags_penalty_points_nonnegative", ADD CONSTRAINT "off_platform_flags_penalty_points_nonnegative" CHECK ("penalty_points_applied" >= 0);