name: CI

on:
  push:
    branches: [main, develop, UAT]
  pull_request:
    branches: [main, develop, UAT]

jobs:
  verify:
    uses: SmartYoungImmortal/AdvisoryPlatformAPI/.github/workflows/verify.yml@b0c04a7c8dd7b10bf405094ec890afdc1bd77daa

  build-container:
    permissions:
      artifact-metadata: write
      attestations: write
      packages: write
      id-token: write
      contents: read
    uses: SmartYoungImmortal/AdvisoryPlatformAPI/.github/workflows/build-container.yml@dc91c13a900a6f70f86bbd2580fc3a9bebeab605
