name: CI

on:
  push:
    branches: [main, develop, UAT]
  pull_request:
    branches: [main, develop, UAT]

jobs:
  verify:
    uses: SmartYoungImmortal/AdvisoryPlatformAPI/.github/workflows/verify.yml@e173d1f2133c84ced8eb3bb855730da4a6c1fad8
    secrets: inherit

  build-container:
    permissions:
      artifact-metadata: write
      attestations: write
      packages: write
      id-token: write
      contents: read
    uses: SmartYoungImmortal/AdvisoryPlatformAPI/.github/workflows/build-container.yml@dc91c13a900a6f70f86bbd2580fc3a9bebeab605
